config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  devise_for :users, controllers: { registrations: 'registrations' }

  resources :polls do
    resources :answers, only: :update
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :poll
  has_many :vote_records, dependent: :destroy

  validates_presence_of :name

  def votes
    VoteRecord.where(answer_id: id).count
  end
end

app/models/poll.rb
class Poll < ActiveRecord::Base
  belongs_to :user
  has_many :answers, dependent: :destroy

  validates_presence_of :name
  accepts_nested_attributes_for :answers, allow_destroy: true
  validates_presence_of :answers
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :polls
  has_many :answers, through: :polls

  validates_presence_of [:first_name, :last_name]
end

app/models/vote_record.rb
class VoteRecord < ActiveRecord::Base
  belongs_to :answer
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def update
    poll = Poll.find(params[:poll_id])
    answer = poll.answers.find(params[:id])

    # Check if vote allowed [ip & session]
    unless user_already_voted?(poll, request.remote_ip)
      vote_record = VoteRecord.new(ip: request.remote_ip, answer: answer)
      vote_record.save
      session['voted_in_poll_' + poll.id.to_s] = true
    end

    # TODO: add some kind of error message to json if vote isnt cast

    render json: poll.to_json(include: { answers: { methods: :votes } })
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :find_poll, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]

  def index
    @polls = Poll.where(user: current_user).order('created_at DESC')
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @poll.to_json(include: { answers: { methods: :votes } }) }
    end
  end

  def new
    @poll = Poll.new
    # Give default 2 answer spaces
    2.times { @poll.answers.build }
  end

  def create
    @poll = current_user.polls.build(poll_params)
    if @poll.save
      flash[:notice] = "Poll created"
      redirect_to @poll
    else
      flash[:alert] = "Poll unable to save"
      render 'new'
    end
  end

  def edit
  end

  def update
    if @poll.update poll_params
      flash[:notice] = "Poll update was successful"
      redirect_to @poll
    else
      render 'edit'
    end
  end

  def destroy
    @poll.destroy
    redirect_to polls_path
  end

  private

  def poll_params
    params.require(:poll).permit(:name, :answers_attributes => [:id, :name, :_destroy])
  end

  def find_poll
    @poll = Poll.find params[:id]
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password,
                                 :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password,
                                 :password_confirmation, :current_password)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @polls = Poll.all.order('created_at DESC')
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_already_voted?(poll, ip)
    vote_records = VoteRecord.where(answer: poll.answers).where(ip: ip)
    session['voted_in_poll_' + poll.id.to_s] == true || vote_records.count > 1
  end
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.haml
!!! 5
%html{ :lang => "en"}
  %head
    %meta{ :charset => "utf-8" }

    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

    %title= content_for?(:title) ? yield(:title) : "Simple Poll"

    = stylesheet_link_tag "application"
    = javascript_include_tag "vendor/modernizr"
    -# = javascript_include_tag '%script{:src => "https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"}'
    = javascript_include_tag "application"
    = csrf_meta_tag

  -# Assign class to body to be able to run javascript on certain pages only
  %body{class: "#{controller_name} #{action_name}" }

    %header
      .row
        .large-12.columns
          %h1
            %a{:href => root_path} Simple Poll
      .row
        .small-8.columns
          %a{:href => root_path} Home
          - if user_signed_in?
            |
            %a{:href => polls_path} My polls
            |
            %a{:href => new_poll_path} New poll
        .small-4.columns
          .right
            - if user_signed_in?
              = link_to "Sign Out", destroy_user_session_path, method: :delete
            - else
              = link_to "Sign Up", new_user_registration_path
              |
              = link_to "Sign In", user_session_path
    %hr/

    .row
      .large-12.columns
        - flash.each do |name, msg|
          - if msg.is_a?(String)
            %div{:class => "alert-box round #{name.to_s == 'notice' ? 'success' : 'alert'}", "data-alert" => ""}
              = content_tag :div, msg
              %a.close{:href => "#"} &#215;
    .row
      .large-12.columns
        = yield

app/views/polls/_answer_fields.html.haml
.large-12.columns
  .nested-fields.field.answer-field
    = f.label :name, "Answer"
    .row.collapse
      .small-10.columns
        = f.text_field :name
      .small-2.columns
        = link_to_remove_association "Remove Answer", f, class: 'button secondary postfix'

app/views/polls/_form.html.haml
=form_for @poll do |f|
  - if @poll.errors.any?
    .row
      .large-12.columns
        %h3= pluralize(@poll.errors.count, 'error') + ' prevented this poll from saving'
        %ul
          - @poll.errors.full_messages.each do |msg|
            %li= msg
  .row
    .large-12.columns
      .field
        = f.label :name, "Name"
        = f.text_field :name, :placeholder=>"Enter your question here..."
        %br/
  .row
    = f.fields_for :answers do |builder|
      = render 'answer_fields', :f => builder
    %br/
    .large-12.columns
      = link_to_add_association 'Add answer', f, :answers, limit: 1, class: 'button secondary'
      = f.submit class: 'button'

app/views/polls/edit.html.haml
.row
  .large-12.columns
    %h2.left
      Edit Poll
    %hr/

=render 'form'

app/views/polls/index.html.haml
.row
  .large-12.columns
    %h2.left My Polls
    %hr/
  - @polls.each do |p|
    .large-12.columns
      %h3.left
        = link_to p.name, poll_path(p)
      .right
        = p.created_at.strftime("%d %b %Y")
      %hr/

app/views/polls/new.html.haml
.row
  .large-12.columns
    %h2.left
      New Poll
    %hr/

=render 'form'

app/views/polls/show.html.haml
.row
  .large-12.columns
    %h2{class: 'left poll_name',  data: { 'poll_id': @poll.id}}
      = @poll.name
    .right
      = @poll.created_at.strftime("%d %b %Y")
    %hr/

  - if !user_already_voted?( @poll, request.remote_ip )
    .large-12.columns.answers
      - @poll.answers.each do |a|
        .vote-container
          %h4
            = a.name
            %a{:href => "#", class: 'button right vote', data: { 'poll_id': @poll.id, 'answer_id': a.id }} Vote
          %hr/


  %div{class: ['large-12', 'columns', 'results', ('hide' if !user_already_voted?( @poll, request.remote_ip ))] }
    - @poll.answers.each do |a|
      .vote-container
        %h4
          = a.name
          %div{class: 'right result', data: { 'answer_id': a.id }}= a.votes.to_s + ' Votes'
        %hr/

  -if @poll.user == current_user
    .large-12.columns
      = link_to 'Edit', edit_poll_path(@poll), class: 'button'
      = link_to 'Delete', poll_path(@poll), method: :delete, class: 'button secondary', data: {confirm: "Are you sure?"}
      - if !user_already_voted?( @poll, request.remote_ip )
        %a{:href => "#", class: 'button secondary',  id: 'show-results'} Show Results

app/views/static_pages/home.html.haml
.row
  .large-12.columns
    %h2.left Latest Polls
    %hr/
  - @polls.each do |p|
    .large-12.columns
      %h3.left
        = link_to p.name, poll_path(p)
      .right
        = p.created_at.strftime("%d %b %Y")
      %hr/